//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoView
    {
        public Nullable<int> huomid { get; set; }
        public Nullable<int> dwid { get; set; }
        public int id { get; set; }
        public string dwname { get; set; }
        public Nullable<int> sfyx { get; set; }
        public string qzzp { get; set; }
        public Nullable<int> isxs { get; set; }
        public Nullable<int> isgy { get; set; }
        public int Expr1 { get; set; }
        public string name { get; set; }
        public Nullable<int> fullflag { get; set; }
        public Nullable<int> sfsh { get; set; }
        public Nullable<int> Expr2 { get; set; }
    }
}
