//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoLogInfoes
    {
        public int Id { get; set; }
        public int CargoId { get; set; }
        public int ShipmentId { get; set; }
        public int HuotId { get; set; }
        public decimal ChangeWeight { get; set; }
        public int CargoInId { get; set; }
        public int StateId { get; set; }
        public string Desc { get; set; }
        public string InspectName { get; set; }
        public Nullable<System.DateTime> InspectTime { get; set; }
        public Nullable<bool> IsIncome { get; set; }
    }
}
