//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheh
    {
        public int DHLS { get; set; }
        public Nullable<int> id { get; set; }
        public string cheh1 { get; set; }
        public string big { get; set; }
        public string small { get; set; }
        public Nullable<int> printflag { get; set; }
        public Nullable<int> weight_flag { get; set; }
        public Nullable<System.DateTime> shij { get; set; }
        public Nullable<int> del_flag { get; set; }
        public Nullable<System.DateTime> del_time { get; set; }
        public string del_person { get; set; }
        public Nullable<int> isphone { get; set; }
        public int ceshi { get; set; }
        public Nullable<int> xhflag { get; set; }
        public string xhqrperson { get; set; }
        public Nullable<System.DateTime> xhqrtime { get; set; }
        public string xhpicurl { get; set; }
        public int door_in { get; set; }
        public int door_out { get; set; }
        public string in_person { get; set; }
        public string out_person { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public int print { get; set; }
        public string in_place { get; set; }
        public string out_place { get; set; }
        public string ip { get; set; }
        public Nullable<int> sfsh { get; set; }
        public Nullable<int> shtg { get; set; }
        public string shry { get; set; }
        public Nullable<System.DateTime> shtime { get; set; }
        public string sjid { get; set; }
        public string newshdd { get; set; }
        public string in_pic { get; set; }
        public string in_pic2 { get; set; }
        public Nullable<int> sfmydts { get; set; }
        public Nullable<int> sjpx { get; set; }
        public string sj_pk { get; set; }
        public string khname { get; set; }
        public Nullable<int> khuserId { get; set; }
        public string zczl { get; set; }
        public int err { get; set; }
        public string err_str { get; set; }
        public Nullable<int> zcflag { get; set; }
        public string ph { get; set; }
        public string zcren { get; set; }
        public string zcshij { get; set; }
        public Nullable<int> zhaoh { get; set; }
        public string zhaoh_yy { get; set; }
        public string zhaoh_sj { get; set; }
        public string zhaoh_p { get; set; }
        public Nullable<int> dais { get; set; }
    }
}
