//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dw
    {
        public int id { get; set; }
        public string dwname { get; set; }
        public Nullable<int> sfyx { get; set; }
        public string qzzp { get; set; }
        public Nullable<int> isxs { get; set; }
        public Nullable<int> isgy { get; set; }
        public string c_dm { get; set; }
        public string c_parentid { get; set; }
        public string qzurl { get; set; }
        public Nullable<int> n_sn { get; set; }
    }
}
