//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class huot
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> qyid { get; set; }
        public string qyname { get; set; }
        public string jd { get; set; }
        public string wd { get; set; }
        public Nullable<int> sfyx { get; set; }
        public Nullable<int> dwid { get; set; }
        public Nullable<int> ssdwid { get; set; }
        public string ip { get; set; }
    }
}
