//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pihao
    {
        public int ID { get; set; }
        public Nullable<int> DHLS { get; set; }
        public string PH_NO { get; set; }
        public Nullable<double> PH_ZL { get; set; }
        public string tihuolx { get; set; }
        public string qianfa { get; set; }
        public string sj { get; set; }
        public int del { get; set; }
        public bool IsChecked { get; set; }
        public string InspectId { get; set; }
        public Nullable<System.DateTime> InspectTime { get; set; }
        public Nullable<int> HuotId { get; set; }
        public string del_time { get; set; }
        public string del_Name { get; set; }
    }
}
