//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbEfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_ry
    {
        public string pk { get; set; }
        public string c_zh { get; set; }
        public string c_mm { get; set; }
        public string c_xm { get; set; }
        public string v_yxbz { get; set; }
        public string c_dh { get; set; }
        public Nullable<int> n_dw { get; set; }
        public string c_openid { get; set; }
        public string c_nc { get; set; }
        public string c_webtoken { get; set; }
        public string c_szdw { get; set; }
        public string c_qxdw { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string dw { get; set; }
        public Nullable<int> qx { get; set; }
        public Nullable<int> dwid { get; set; }
        public Nullable<int> lx { get; set; }
        public string devicecode { get; set; }
        public string ip { get; set; }
        public Nullable<int> htid { get; set; }
        public Nullable<int> sfyx { get; set; }
        public string qzurl { get; set; }
        public string zgqzurl { get; set; }
        public Nullable<int> qyid { get; set; }
        public string tel { get; set; }
    }
}
